name: RushCrossFit
favicon: null
layout_spectrum: 0.33384
typography_spectrum: 0.31642
title: Home Page
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#fefefe'
    - '#a5a6a0'
    - '#72736d'
    - '#cbccc6'
  brandStrength: 0.8125
  lightness: 0.7502800095826387
  saturation: 0.6970381133724004
  rhythmicContrast: 0.4766018697991967
purpose: []
